
# Only sourced by login shells. Hence, if $PATH is set in this file it's not set
# when logging in through a DE such as LightDM. Also terminals such as termite.
#
# In archlinux, /etc/profile is sourced from /etc/zsh/zprofile causing the $PATH
# to be overwritten if set in .zshenv
#
# See https://lists.archlinux.org/pipermail/arch-general/2013-March/033108.html

# vim: ft=zsh cms=#%s
