
# completion
autoload -U compinit && compinit

# correction
#setopt correctall

autoload -U colors && colors

# http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable cvs git
zstyle ':vcs_info:git*' check-for-changes true
zstyle ':vcs_info:git*' check-for-staged-changes true
zstyle ':vcs_info:git*' check-for-unstaged-changes true
zstyle ':vcs_info:git*' stagedstr "%F{green}*"
zstyle ':vcs_info:git*' unstagedstr "%F{yellow}*"

setopt PROMPT_SUBST
precmd() { 
    if [[ -z $(git ls-files --other --exclude-standard 2> /dev/null) ]] {
        zstyle ':vcs_info:git*' formats "%F{blue}[%b%c%u%]%F{blue}]%{$reset_color%}"
    } else {
        zstyle ':vcs_info:git*' formats "%F{blue}[%b%c%u%F{red}*%F{blue}]%{$reset_color%}"
    }

    vcs_info 
}

PROMPT="[%n@%m %1~] %# "
RPROMPT='${vcs_info_msg_0_}'

bindkey -e                      # Use emacs shortcuts

# Automatic history search with arrow keys
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward

# history
mkdir -p $XDG_DATA_HOME/zsh     # Create folder if not existing
HISTFILE=$XDG_DATA_HOME/zsh/history
HISTSIZE=1000
SAVEHIST=1000
setopt HIST_IGNORE_ALL_DUPS     # Delete older duplicates from history
setopt INC_APPEND_HISTORY       # Incrementally append history from all sessions continously
setopt EXTENDED_HISTORY         # Save time when command was entered
setopt HIST_IGNORE_SPACE        # Line beginning with space is not saved

# aliases
alias ls="ls --color=auto -F"
alias ll="ls --color=auto -lh"
alias spm="sudo pacman"
alias cower="cower -c"
alias diff="colordiff"
alias tmux="tmux -f '$XDG_CONFIG_HOME'/tmux/tmux.conf"
#export TMUX_TMPDIR="$XDG_RUNTIME_DIR"/tmux  # Keep?

#zstyle ':completion:*:pacman:*' force-list always
#zstyle ':completion:*:*:pacman:*' menu yes select

#zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# vim: ft=zsh cms=#%s
